comments/urls.py
from django.conf.urls import url

from .views import add_comment


urlpatterns = [
    url(
        r'^$',
        add_comment,
        name='add_comment'
    ),
]

news/urls.py
from django.conf.urls import url

from .views import PostDetailView, like_add


urlpatterns = [
    url(
        r'^post-detail/(?P<pk>\d+)/$',
        PostDetailView.as_view(),
        name='post_detail',
    ),
    url(
        r'^likes/$',
        like_add,
        name='like_add',
    ),
]

techscopes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from news.views import PostsListView

urlpatterns = [
    url(r'^$', PostsListView.as_view(), name='main'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.conf import settings

from django.contrib.contenttypes.fields import GenericForeignKey, \
    GenericRelation
from django.contrib.contenttypes.models import ContentType


class Comment(models.Model):
    published = models.DateTimeField('When published',
                                     auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               verbose_name='Author',
                               related_name='comments')
    text = models.CharField('Comment text', max_length=500)
    reply_to = models.ForeignKey('self', blank=True, null=True)
    is_hidden = models.BooleanField('Is hidden', default=False)
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={'model__in': ('post', 'comment')}
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    reply = GenericRelation(
        'comments.Comment',
        related_query_name='comments'
    )

    class Meta:
        verbose_name = 'Comments'
        verbose_name_plural = 'Comment'

    def __unicode__(self):
        return '%s %s' % (self.author, self.text)

    def get_content_type(self):
        return ContentType.objects.get_for_model(self).id

news/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey, \
    GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse

from comments.models import Comment


class Like(models.Model):
    when_created = models.DateTimeField(
        'When created',
        auto_now_add=True
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='Author',
        related_name='likes'
    )
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={'model__in': ('post',)}
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = 'Like'
        verbose_name_plural = 'Likes'

    def __unicode__(self):
        return '%s - author: %s' % (self.content_type.name,
                                    self.author.username)


class PostManager(models.Manager):
    def news(self, *args, **kwargs):
        kwargs['rubric'] = self.model.NEWS
        return self.filter(*args, **kwargs)


class Post(models.Model):
    NEWS = 'NEWS'
    RUBRIC_CHOICES = (
        (NEWS, 'News'),
    )
    when_created = models.DateTimeField(
        'When created',
        auto_now_add=True
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='Author',
        related_name='posts'
    )
    title = models.CharField('Title', max_length=100)
    text = models.TextField('Text')
    rubric = models.CharField(
        max_length=10,
        verbose_name='Rubric',
        choices=RUBRIC_CHOICES,
        blank=True
    )
    image = models.ImageField('Image', upload_to='post_news',
                              blank=True, null=True)
    comments = GenericRelation(Comment, related_query_name='posts')
    likes = GenericRelation(Like, related_query_name='posts')
    objects = PostManager()

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __unicode__(self):
        return '%s - author: %s' % (self.title, self.author.username)

    def get_absolute_url(self):
        return reverse('news:post_detail', args=(self.pk,))

    def get_content_type(self):
        return ContentType.objects.get_for_model(self).id

    def get_comments_amount(self):
        return self.comments.count() + \
               sum(comment.reply.count() for comment in self.comments.all())

news/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseBadRequest
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.views.generic import DetailView
from django.views.generic import ListView

from news.models import Like, Post

COMMENTS_PER_LIST = 3


class PostsListView(LoginRequiredMixin, ListView):
    template_name = 'main.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        """Return a queryset sorted by a date of creation in descending order.
        If the parameter 'Sort by' is defined, returns a queryset according to
        this parameter."""
        q = self.request.GET.get('q')
        sort_by = self.request.GET.get('sort_by')
        queryset = Post.objects.all().order_by('-when_created')
        if q:
            queryset = Post.objects.filter(text__contains=q)
        elif sort_by and len(sort_by) > 0:
            sort_by = sort_by.lower()
            if sort_by == 'country':
                queryset = Post.objects.all().order_by(
                    'author__profile__country')
            if sort_by == 'city':
                queryset = Post.objects.all().order_by('author__profile__city')
        return queryset

    def get_context_data(self, **kwargs):
        context = super(PostsListView, self).get_context_data(**kwargs)
        q = self.request.GET.get('q')
        sort_by = self.request.GET.get('sort_by')
        if q:
            context['q'] = q
        elif sort_by:
            context['sort_by'] = sort_by
        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'news/post_detail.html'
    pk_url_kwarg = 'pk'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        # Paginate comments
        comments_list = self.object.comments.order_by('-published')
        paginator = Paginator(comments_list, COMMENTS_PER_LIST)
        page = self.request.GET.get('page')
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)
        context['comments'] = comments
        return context


class HttpResponseSeeOther(HttpResponseRedirect):
    status_code = 303


@login_required
@require_POST
def like_add(request):
    """Function adds like to a post. If the post already has like from this
    user, function deletes user's like for the post."""
    content_type = request.POST.get('content_type', None)
    object_id = request.POST.get('object_id', None)
    if content_type and object_id:
        content_type = ContentType.objects.get_for_id(content_type)
        try:
            content_type.get_object_for_this_type(pk=object_id)
        except ObjectDoesNotExist:
            return HttpResponseBadRequest()
        like_queryset = Like.objects.filter(author=request.user,
                                            content_type=content_type,
                                            object_id=object_id)

        if like_queryset.exists():
            like_queryset.delete()
            return JsonResponse({"removed_like": True}, status=200)
        new_like = Like(author=request.user,
                        content_type=content_type,
                        object_id=object_id)
        new_like.save()
        return JsonResponse({"added_like": True}, status=200)
    return JsonResponse({}, status=404)

news/templates/news/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ post.header }}
{% endblock title %}

{% block content %}
    <div class="left-sidebar" style="width: 10%">
    </div>
    <div class="big-middle-box">
        <div class="post-body-box-article">
            <div class="post-body-head-box-article" >
                <div class="post-body-about-box-article">
                    <div class="post-body-about-title-article">
                        <span>The article published by &nbsp<a href="">{{ post.author.username }}</a></span>
                    </div>
                    <div class="post-body-about-info-aricle">{{ post.author.get_full_name }}</div>
                </div>
            </div>
            {% if post.image %}
                <div class="main-post-photo-box" >
                    <div class="post-item-photo-box">
                        <div class="post-item-main-photo">
                            <a href="#"><img src="{{ post.image.url }}" width="920" height="483"></a>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="post-body-text-box-article" >
                <h4><a href="#" >{{post.title}}</a></h4>
                    {{ post.text|safe }}
                 <div class="post-item-info-block" >
                    <div class="post-item-like">
                            <button class="like-button"
                                    data-url="{% url 'news:like_add' %}"
                                    data-counter="#likes_{{ post.get_content_type }}_{{ post.pk }}"
                                    data-content_type="{{ post.get_content_type }}"
                                    data-object_id="{{ post.pk }}">
                                Like
                            </button>
                            <span id="likes_{{ post.get_content_type }}_{{ post.pk }}">{{ post.likes.count }}</span>
                    </div>
                    <div class="post-item-link">
                        <a class="post-item-old-link" href="#">{{ post.published|date:"d.n.Y" }}</a>
                        <a id=item-comment-link class="post-item-comment-link" href="#">{{ post.get_comments_amount }} Comments</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="main-message-send-article">
            <form name="form_massage-article" action="{% url 'comments:add_comment' %}" method="POST" id="comment_form" >{% csrf_token %}
                <input type='hidden' name="object_id" value="{{ post.id }}" />
                <input type='hidden' name="content_type" value="{{ post.get_content_type }}" />
                <textarea class="block_massage_answer-article" id="block_massage_main-article" name="text" form="comment_form" placeholder="Type the text.." required="required"></textarea>
                <input type="submit" value="SEND" class="but_massage_send-aricle">
            </form>
        </div>
        <div id="comment_user" class="comment_user_lost">
            {% for comment in comments %}
                <div class="user_lost">
                    <div class="post-body-head-box-comment">
                        <div class="post-body-about-box-comment">
                            <div class="post-body-about-title-comment">
                                <span><a href="#">{{ comment.author.username }}</a></span>
                            </div>

                        </div>
                        <div class="post-body-service-box-comment">
                            <p>{{ comment.text|safe|linebreaks }}</p>
                        </div>
                    </div>
                    <div class="main-message-answer-article">
                        <form name="form_massage-article" action="{% url 'comments:add_comment' %}" method="POST" id="reply_form_{{ forloop.counter }}" >{% csrf_token %}
                            <input type='hidden' name="object_id" value="{{ comment.id }}" />
                            <input type='hidden' name="content_type" value="{{ comment.get_content_type }}" />
                            <input type='hidden' name="reply_to" value="{{ comment.id }}" />
                            <textarea class="block_massage_answer-article" name="text" form="reply_form_{{ forloop.counter }}" placeholder='Type the text..' required="required"></textarea>
                            <input type="submit" value="Answer" class="but_massage_send-aricle">
                        </form>
                    </div>
                </div>
                {% for reply in comment.comment_set.all %}
                    <div class="user_lost" style="padding: 5px 0 0;margin: -10px 0px;background-color: #b7b7b7">
                        <div class="post-body-head-box-comment">
                            <div class="post-body-about-box-comment">
                                <div class="post-body-about-title-comment">
                                    <span><a href="#" style="color: #4e71a8">{{ reply.author.username }}</a></span><div class='answer_to'><i></i><a href='#' style="color: #4e71a8">{{ reply.author.username }}</a></div>
                                </div>
                            </div>
                            <div class="post-body-service-box-comment">
                                <p>{{ reply.text|safe|linebreaks }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
            {% if comments.paginator and comments.has_other_pages %}
                <div class="border_pagin">
                    <ul class="vkladka">
                        {% if comments.has_previous %}
                            <li><a class="arrow-vklad" href="?page={{ comments.previous_page_number }}">&lt;</a></li>
                        {% endif %}

                        {% for page in comments.paginator.page_range %}
                            {% if page == comments.number %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li>
                            {% else %}
                                <li><a href="?page={{ page }}" style="background-color: #7c7c7c;">{{ page }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if comments.has_next %}
                            <li><a class="arrow-vklad" href="?page={{ comments.next_page_number }} }}">&gt;</a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}


{% block js %}
    <script defer type="application/javascript" src="{% static 'js/like.js' %}"></script>
    <script defer type="application/javascript" src="{% static 'js/toggle_comments.js' %}"></script>
{% endblock js %}