accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import account_activation_sent, activate, signup


urlpatterns = [
    url(
        r'^login/$',
        auth_views.login,
        {'template_name': 'accounts/login.html'},
        name='login'
    ),
    url(
        r'^logout/$',
        auth_views.logout,
        {'next_page': 'accounts:login'},
        name='logout'
    ),
    url(
        r'^signup/$',
        signup,
        name='signup'
    ),
    url(
        r'^account_activation_sent/$',
        account_activation_sent,
        name='account_activation_sent'
    ),
    url(
        r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'
    ),
]

news/urls.py
from django.conf.urls import url

from .views import PostDetailView, like_add


urlpatterns = [
    url(
        r'^post-detail/(?P<pk>\d+)/$',
        PostDetailView.as_view(),
        name='post_detail',
    ),
    url(
        r'^likes/$',
        like_add,
        name='like_add',
    ),
]

techscopes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from news.views import PostsListView

urlpatterns = [
    url(r'^$', PostsListView.as_view(), name='main'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    email = models.EmailField('email address', unique=True, db_index=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    birth_date = models.DateField(null=True, blank=True)
    country = models.CharField(max_length=30, blank=True)
    city = models.CharField(max_length=30, blank=True)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return self.user.email


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from accounts.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254,
        help_text='Required. Please input a valid email address.'
    )
    birth_date = forms.DateField(
        help_text='Not required. Format: YYYY-MM-DD'
    )
    country = forms.CharField(
        max_length=30,
        help_text='Not required. Not required. 30 characters or fewer'
    )
    city = forms.CharField(
        max_length=30,
        help_text='Not required. 30 characters or fewer'
    )

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2',
            'birth_date',
            'country',
            'city'
        )

accounts/views.py
from django.contrib.auth import login
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from .models import User
from .forms import SignUpForm
from .tokens import account_activation_token


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user.refresh_from_db()
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.profile.country = form.cleaned_data.get('country')
            user.profile.city = form.cleaned_data.get('city')
            user.save()
            # Send the account activation email for the user
            current_site = get_current_site(request)
            subject = 'Activate Your Techscopes Account'
            message = render_to_string(
                'accounts/account_activation_email.html',
                {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                }
            )
            user.email_user(subject, message)
            return redirect('accounts:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'accounts/account_activation_sent.html')


def activate(request, uidb64, token):
    """Check if the user exists, if the token is valid. Switch the flags
    is_active and email_confirmed to True and log the user in. By changing the
    value of the email_confirmed field, it will cause the link to be
    invalidated."""
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('main')
    else:
        return render(request, 'accounts/account_activation_invalid.html')

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration on Techscopes:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/account_activation_invalid.html
{% extends 'base.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

accounts/templates/accounts/account_activation_sent.html
{% extends 'base.html' %}

{% block content %}
    <div class="main-pop-up-login" style="width: 570px">
        <p>Please confirm your email address to complete the registration and go to</p>
        <a href="{% url 'accounts:login' %}"><h4>log in</h4></a>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% load static %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Now is Better Than Never{% endblock %}</title>
  </head>
  <body>
  <div class="main-login" style="margin: 170px auto;display: table;border-radius: 10px;width: 550px;padding: 20px;box-sizing: border-box;
box-shadow: 2px 3px 9px 2px rgba(0,0,0,0.56);
    background-color: #fff;
    position: relative;
    z-index: 20;">
    <h2>Log in to Techscopes</h2>
      <form method="post">
        {% csrf_token %}
          <input type="hidden" name="next" value="{{ next }}" />
          {% bootstrap_form form %}
          {% buttons %}
              <button type="submit" class="btn btn-primary">Log in</button>
          {% endbuttons %}
      </form>
    <a href="{% url 'accounts:signup' %}"><h4>New to Techscopes? Sign up</h4></a>
  </div>
  </body>
</html>

accounts/templates/accounts/signup.html
{% load static %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Now is Better Than Never{% endblock %}</title>
  </head>
  <body>
    <div class="main-pop-up-login" style="margin: 10px auto;display: table;border-radius: 10px;width: 550px;padding: 20px;box-sizing: border-box;box-shadow: 2px 3px 9px 2px rgba(0,0,0,0.56);position: relative;z-index: 20;">
    <h2 style="text-align: center;">Sign up to Techscopes</h2>
      <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
              <button type="submit" class="btn btn-primary">Sign up</button>
          {% endbuttons %}
      </form>
    </div>
  </body>
</html>